version: "3.8"
services:
  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static-data:/srv/public
    ports:
      - 1337:80
    networks:
      - network

networks:
  network:
    external:
      name: nginx_network

volumes:
  postgresql-data:
  static-data:
